name: Build_Test_Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM Depencencies
      run: npm install
    - name: Run the unit tests
      run: npm run test:unit
    - name: Display SoftUni username
      run: echo 'Stasi03'

  build_ui-tests:
    needs: build_unit-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 21.x
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        cache: 'npm'
    - name: Install NPM Depencencies
      run: npm install
    - name: Install Playwright Browsers
      run: npx playwright install
    - name: Start App
      run: npm start &
    - name: Run the ui tests
      run: npm run test:ui

  deploy:
    needs: build_ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api_key: ${{ secrets.MY_RENDER_API_KEY }}
          wait_deploy: true

